export enum CartStatus {
  OPEN = 'OPEN',
  CHECKOUT = 'CHECKOUT',
  WAITING_PAYMENT = 'WAITING_PAYMENT',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYMENT_MISMATCH = 'PAYMENT_MISMATCH',
  ORDERED = 'ORDERED',
  ABANDONED = 'ABANDONED',
}
